### ISSUE TITLE
missing db.Close() 

### ISSUE THREAD

**Issue by willis7** [gophercises/task#1]
Great tutorial, but I'm missing where we close the db. Is that a purposeful omission or accidental?

**Comment by joncalhoun** [comment]
Probably accidental. 🤦‍♂️

**Comment by willis7** [comment]
I overcame this myself by adding the following to `db/tasks.go`

```
func Close() {
    db.Close()
}
```

and then to my main.go

```
...
must(db.Init(dbPath))
defer db.Close()
must(cmd.RootCmd.Execute())
...
```

**Comment by joncalhoun** [comment]
I need to dig further, but I'm like 90% sure that your application exiting (like this does) will result in the db connection closing fine so it may not matter, but again I want to make sure that is correct and make note of it in the exercise regardless. Thanks for pointing this out :)

**Comment by ashnair1** [comment]
So does it not matter?
